FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Framework" = "*", "Sedulous.Platform" = "*", SDL2 = "*", "Sedulous.Renderer" = "*", "Sedulous.RHI.Vulkan" = "*", "Sedulous.Audio" = "*", "Sedulous.GAL" = "*", "Sedulous.GAL.Vulkan" = "*", "Sedulous.Graphics" = "*", "Sedulous.Graphics.Vulkan" = "*"}

[Project]
Name = "Sedulous.Framework.SDL"
TargetType = "BeefLib"
StartupObject = "Sedulous.Framework.SDL.Program"
