FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Framework" = "*", "Sedulous.Platform" = "*", SDL2 = "*"}

[Project]
Name = "Sedulous.SDL"
TargetType = "BeefLib"
StartupObject = "Sedulous.SDL.Program"
