FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.SDL" = "*", "Sedulous.Graphics" = "*", "Sedulous.Graphics.Vulkan" = "*"}

[Project]
Name = "GraphicsTest"
StartupObject = "GraphicsTest.Program"
