FileVersion = 1
Dependencies = {corlib = "*", Dxc-Beef = "*"}

[Project]
Name = "Sedulous.Graphics.HLSLShaderCompiler"
TargetType = "BeefLib"
StartupObject = "Sedulous.Graphics.HLSLShaderCompiler.Program"
