FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Framework" = "*", SPIRV-Cross = "*", Dxc-Beef = "*", "Sedulous.GAL" = "*", "Sedulous.SDL" = "*", "Sedulous.GAL.Vulkan" = "*"}

[Project]
Name = "Sandbox"
StartupObject = "Sandbox.Program"
