FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Framework" = "*", "Sedulous.Framework.SDL" = "*", SPIRV-Cross = "*", Dxc-Beef = "*"}

[Project]
Name = "Sandbox"
StartupObject = "Sandbox.Program"
