FileVersion = 1
Dependencies = {corlib = "*", "Sedulous.Foundation" = "*", "Sedulous.Platform" = "*"}

[Project]
Name = "Sedulous.GAL"
TargetType = "BeefLib"
StartupObject = "Sedulous.Graphics.Program"
DefaultNamespace = "Sedulous.Graphics"
ProcessorMacros = ["VALIDATE_USAGE"]
